/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_justTest_SqrtNativeVsBasicRunner */

#ifndef _Included_com_justTest_SqrtNativeVsBasicRunner
#define _Included_com_justTest_SqrtNativeVsBasicRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_justTest_SqrtNativeVsBasicRunner
 * Method:    nativeCSqrt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_justTest_SqrtNativeVsBasicRunner_nativeCSqrt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
