/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_justTest_SqrtNativeVsBasicRunner_ExecutionPlan */

#ifndef _Included_com_justTest_SqrtNativeVsBasicRunner_ExecutionPlan
#define _Included_com_justTest_SqrtNativeVsBasicRunner_ExecutionPlan
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
